export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_PENDING = 'GET_USERS_PENDING'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_PENDING = 'GET_POSTS_PENDING'
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED'

export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS'
export const GET_ALBUMS_PENDING = 'GET_ALBUMS_PENDING'
export const GET_ALBUMS_FAILED = 'GET_ALBUMS_FAILED'

export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS'
export const GET_PHOTOS_PENDING = 'GET_PHOTOS_PENDING'
export const GET_PHOTOS_FAILED = 'GET_PHOTOS_FAILED'

export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_PENDING = 'GET_COMMENTS_PENDING'
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED'
